<a href="https://colab.research.google.com/github/sanit15/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


In [ ]:
import torch
import pandas as ds
print(torch.__version__)

2.11.0+cpu


##Introduction to tensors
###Creating Tensors



In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8],
                [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [2,3,4],
                       [3,4,5]],
                       [[1, 2, 3],
                        [1, 3, 4],
                        [1, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]],

        [[1, 2, 3],
         [1, 3, 4],
         [1, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

### Random Tensor

Why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> repeat `

In [ ]:
#create a random tensor of size (3, 4)
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.6613, 0.9592, 0.6583, 0.3607],
        [0.4220, 0.7512, 0.8984, 0.3804],
        [0.9522, 0.8885, 0.3150, 0.8246]])

In [ ]:
rand_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
rand_img_size_tensor = torch.rand(size=(224, 224, 3)) #height width, color channel(R,G,B)
rand_img_size_tensor.shape, rand_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
### Zeros and Ones
zeros = torch.zeros(size=(3,4))
zeros*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
## creating a range of tensors and tensor-like
torch.arange(0,10) # range is 0 to n-1
ones_to_tens = torch.arange(0, 1000, 77)
ones_to_tens

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
 #creating tensor like
ten_zeros =  torch.zeros_like(input=ones_to_tens)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#float 32 tensor
float_tensor_float = torch.tensor([3.0,6.0, 9.0],
                            dtype= None, #datatype of tensor
                            device = None,#operation device cpu, cuda
                            requires_grad= False)#gradient tracking
float_tensor_float

tensor([3., 6., 9.])

In [ ]:
tensor1 = float_tensor_float.type(torch.half)
tensor1

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_tensor_float*tensor1


tensor([ 9., 36., 81.])

#getting info from tensor
1. Tensors not right dtype = to do get dataype from tensor, can use 'tensor.dtype'
2. Tensors not right shape = to get shape from a tensor, can use 'tensor.shape
3. Tensor not on right device = can use tensor.device


In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4176, 0.3293, 0.5335, 0.1231],
        [0.0430, 0.1705, 0.8302, 0.7003],
        [0.5399, 0.5698, 0.9347, 0.8541]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")#can also use tensor.size()
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4176, 0.3293, 0.5335, 0.1231],
        [0.0430, 0.1705, 0.8302, 0.7003],
        [0.5399, 0.5698, 0.9347, 0.8541]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###manipulating a tensor
Tensor includes operations!
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
#inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

##Matrix multiplication

Two types:
1. element wise multiplication
2. Dot product

In [ ]:
#Elementwise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#dot product
%%time
torch.matmul(tensor, tensor)

CPU times: user 300 µs, sys: 1.06 ms, total: 1.36 ms
Wall time: 11.8 ms


tensor(14)

In [ ]:
%%time
tensor @ tensor


CPU times: user 102 µs, sys: 16 µs, total: 118 µs
Wall time: 123 µs


tensor(14)

In [ ]:
#matrix mul by self
%%time
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

NameError: name 'value' is not defined

In [ ]:
###one of the most common error: shape error
### inner shape must match, result is outer dimmensions
## (3,2) @ (2,3) will work ruslut is (3,3)
## (3,2) @ (3,2) wont work

In [ ]:
t1 = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
t2 = torch.tensor([[10,11],
                   [12,13],
                   [14,15]])
t1.shape, t2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
t1.T.shape,t2.T.shape


(torch.Size([2, 3]), torch.Size([2, 3]))

In [ ]:
torch.matmul(t1,t2.T), torch.matmul(t1,t2.T).shape


(tensor([[ 32,  38,  44],
         [ 74,  88, 102],
         [116, 138, 160]]),
 torch.Size([3, 3]))

In [ ]:
##tensor aggregation
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
torch.mean(x.type(torch.float32)) #NEEDS TYPE OF FLOAT32

tensor(45.)

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [ ]:
##FInding the positonal min and
x.argmin(),x.argmax() #pos of min value returns index

(tensor(0), tensor(9))

In [ ]:
x[0],x[9]

(tensor(0), tensor(90))

## Reshaping, Stacking, Squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view oif the input tensorof a certain shape but keep the same memory
* Stacking - combines multi tensors on top of each other or side by side
* Squeeze - removes all `1` dim target tensors
* Unsqueeze - adds a `1` dim to a target
* permute - return a view of the input with dimensions permuted in a certain way

In [ ]:
#lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshape = x.reshape(9,1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#change the view
z = x.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#hence changing z changes x
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on top of each other
x_stack = torch.stack([x,x,x,x], dim = 1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_squeeze = torch.squeeze(x_reshape)
x_squeeze, x_squeeze.shape ## removes dim1 and hence 1,9 -> 9

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#torch.unsqueze() - adds a single dim to target at specific dim
x_unsqueezed = torch.unsqueeze(x_squeeze, dim=0)
x_unsqueezed, x_unsqueezed.shape
#

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#torch.permute()
x_original = torch.rand(size=(2,2,3)) # height, width, color_channel
x_permuted = x_original.permute(2,0,1) # color_channel, height, width
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
x_original, x_permuted

Previous shape: torch.Size([2, 2, 3])
New shape: torch.Size([3, 2, 2])


(tensor([[[0.5671, 0.6534, 0.3345],
          [0.5933, 0.7616, 0.3912]],
 
         [[0.2176, 0.5621, 0.1883],
          [0.5289, 0.1285, 0.2026]]]),
 tensor([[[0.5671, 0.5933],
          [0.2176, 0.5289]],
 
         [[0.6534, 0.7616],
          [0.5621, 0.1285]],
 
         [[0.3345, 0.3912],
          [0.1883, 0.2026]]]))

In [ ]:
##indexing with pytorch
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#lets index
x[0],x[0][0],x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [ ]:
# can use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#get all values of dim 0 but only 1 index of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
#index to get 9
x[:,2,2],x[:,:,2].T

(tensor([9]),
 tensor([[3],
         [6],
         [9]]))

##PyTorch tensors & Numpy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
#Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array )# default is float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#change value of array
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [ ]:
tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

##Reproducability
in short how a neural network works
`start with random numbers -> tensor operations -> update random numbers to try and make them better rpresentation of the date -> repeat`

To reduce randomness in neural network we use of concept of a **random seed**

In [ ]:
##Reproducibility(trying to take random out of random)
rand1 = torch.rand(3,4)
rand2 = torch.rand(3,4)
print(rand1)
print(rand2)
print(rand1 == rand2)

tensor([[0.9037, 0.8739, 0.6610, 0.6457],
        [0.0704, 0.1020, 0.8666, 0.2992],
        [0.0268, 0.1237, 0.3547, 0.4070]])
tensor([[0.0397, 0.7180, 0.7465, 0.7734],
        [0.5657, 0.4520, 0.9618, 0.6572],
        [0.8338, 0.3647, 0.1477, 0.7350]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#lets make a random but reproducable tensor
import torch
#set random seed
rand_seed = 42
torch.manual_seed(rand_seed)
rand1 = torch.rand(3,4)
torch.manual_seed(rand_seed)
rand2 = torch.rand(3,4)
print(rand1)
print(rand2)
print(rand1 == rand2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch obj on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUD + Nvidia hardware + pytorch working behind the scenes to make everything hunky dory(good)

### 1. Getting a GPU

1. Easiest to use google colab tpo get free gpu(option to upgrade)
2. purchasing a gpu
3. cloud computing - GCP, AWS, Azure

In [ ]:
!nvidia-smi

Tue Jun 30 16:43:00 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
###2. Check for gpu access
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of device
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the gpu

The reason we want out tensors/model on gpu as gpu leads to faster computation

In [ ]:
#create a tensor
tensor  = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [ ]:
tensor_gpu = tensor.to(device)
tensor_gpu.device

device(type='cuda', index=0)

## 4. Moving tensor back to cpu

In [ ]:
##if tensor on gpu cant tansform it to numnpy
##to fix first set to cpu
tensor_back_cpu = tensor_gpu.cpu().numpy()
tensor_back_cpu

array([1, 2, 3])