# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.2949, 0.5055, 0.5291, 0.9535, 0.3604, 0.4966, 0.5281],
        [0.8806, 0.4149, 0.6520, 0.2448, 0.5784, 0.6021, 0.4779],
        [0.2048, 0.4376, 0.0248, 0.7126, 0.6716, 0.0842, 0.6214],
        [0.1422, 0.3158, 0.1067, 0.6598, 0.8275, 0.5743, 0.0585],
        [0.8181, 0.7706, 0.3547, 0.9403, 0.6312, 0.3292, 0.7170],
        [0.7130, 0.9775, 0.6511, 0.8882, 0.8668, 0.5551, 0.1841],
        [0.6815, 0.4617, 0.0675, 0.9319, 0.2555, 0.9167, 0.4138]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor1 = torch.rand(1,7)
print(tensor1)
# Perform matrix multiplication
print(torch.matmul(tensor, tensor1.T))

tensor([[0.6792, 0.5903, 0.0706, 0.5388, 0.4420, 0.1504, 0.8705]])
tensor([[1.9135],
        [1.3645],
        [2.1517],
        [1.7294],
        [2.5318],
        [1.5801],
        [1.6731]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
torch.manual_seed(0)
t1 = torch.rand(7,7)
# Create two random tensors
t2 = torch.rand(1,7)
# Matrix multiply tensors
print(torch.matmul(t1, t2.T))
# Create two random tensors


# Matrix multiply tensors


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [3]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [1]:
# Set random seed
import torch
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
tens1 = torch.rand(2,3).to(device)
tens2 = torch.rand(2,3).to(device)
print(tens1)
print(tens2)

tensor([[0.2089, 0.7846, 0.7988],
        [0.2376, 0.1910, 0.5949]], device='cuda:0')
tensor([[0.1913, 0.9465, 0.0295],
        [0.0479, 0.6708, 0.5484]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [4]:
# Perform matmul on tensor_A and tensor_B
tensor_matmul = torch.matmul(tens1, tens2.T)
tensor_matmul

tensor([[0.8062, 0.9743],
        [0.2438, 0.4657]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [5]:
# Find max
tensor_matmul.max(), tensor_matmul.min()
# Find min


(tensor(0.9743, device='cuda:0'), tensor(0.2438, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [6]:
# Find arg max
tensor_matmul.argmax(), tensor_matmul.argmin()

# Find arg min


(tensor(1, device='cuda:0'), tensor(2, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [7]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_new = tensor.squeeze()

# Print out tensors and their shapes
tensor, tensor.shape, tensor_new, tensor_new.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))